# Generated by Django 5.1.3 on 2025-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
