# Generated by Django 5.1.2 on 2024-11-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='item_url',
            new_name='url',
        ),
    ]
