# Generated by Django 5.1.2 on 2024-11-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0005_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
